export const LOAD_DATA = "LOAD_DATA";
export const RETRIEVE_ALL_RECIPES = "RETRIEVE_ALL_RECIPES";
export const FIND_ONE_RECIPES = "FIND_ONE_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const FILTER_RECIPE = "FILTER_RECIPE";
